spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs